services:
  - type: web
    name: backend-service
    env: dotnet
    plan: free
    buildCommand: "dotnet publish -c Release"
    startCommand: "dotnet backend/bin/Release/net8.0/backend.dll"
    rootDir: backend
